import './styles/style.scss';

//Core UI
import {
    // Layout
    CContainer,
    CRow,
    CCol,

    // Components
    CAccordion,
    CAccordionItem,
    CAccordionHeader,
    CAccordionBody,
    CAlert,
    CAvatar,
    CBadge,
    CBreadcrumb,
    CBreadcrumbItem,
    CButton,
    CLoadingButton,
    CButtonGroup,
    CCallout,
    CCard,
    CCardHeader,
    CCardTitle,
    CCardSubtitle,
    CCardImage,
    CCardImageOverlay,
    CCardBody,
    CCardText,
    CCardLink,
    CCardFooter,
    CCarousel,
    CCarouselItem,
    CCloseButton,
    CCollapse,
    CDropdown,
    CDropdownToggle,
    CDropdownMenu,
    CDropdownItem,
    CDropdownDivider,
    CDropdownHeader,
    CFooter,
    CHeader,
    CHeaderToggler,
    CImage,
    CLink,
    CListGroup,
    CListGroupItem,
    CModal,
    CModalHeader,
    CModalTitle,
    CModalBody,
    CModalFooter,
    CNav,
    CNavItem,
    CNavLink,
    CNavGroup,
    CNavTitle,
    CTabContent,
    CTabPane,
    CNavbar,
    CNavbarBrand,
    CNavbarNav,
    CNavbarText,
    CNavbarToggler,
    COffcanvas,
    COffcanvasHeader,
    COffcanvasTitle,
    COffcanvasBody,
    CPagination,
    CPaginationItem,
    CSmartPagination,
    CPlaceholder,
    CPopover,
    CProgress,
    CProgressBar,
    CSidebar,
    CSidebarBrand,
    CSidebarNav,
    CSidebarToggler,
    CSidebarHeader,
    CSidebarFooter,
    CSmartTable,
    CSpinner,
    CTable,
    CTableCaption,
    CTableHead,
    CTableBody,
    CTableRow,
    CTableDataCell,
    CTableHeaderCell,
    CToaster,
    CToast,
    CToastHeader,
    CToastBody,
    CTooltip,
    CWidgetStatsA,
    CWidgetStatsB,
    CWidgetStatsC,
    CWidgetStatsD,
    CWidgetStatsE,
    CWidgetStatsF,

    // Forms
    CForm,
    CFormCheck,
    CDatePicker,
    CDateRangePicker,
    CFormFloating,
    CFormInput,
    CInputGroup,
    CInputGroupText,
    CMultiSelect,
    CFormLabel,
    CFormPlugin,
    CFormText,
    CFormFeedback,
    CFormRange,
    CFormSelect,
    CFormSwitch,
    CFormTextarea,
    CTimePicker
} from '@coreui/vue-pro';
import { CIcon } from '@coreui/icons-vue'
import { CChart } from '@coreui/vue-chartjs'

// Custom
import ReAppBreadcrumb from './components/ReAppBreadcrumb/ReAppBreadcrumb.vue';
import ReAppFooter from './components/ReAppFooter/ReAppFooter.vue';
import ReAppHeader from './components/ReAppHeader/ReAppHeader.vue';
import ReAppSidebar from './components/ReAppSidebar/ReAppSidebar.vue';
import ReCardHeader from './components/ReCardHeader/ReCardHeader.vue';
import ReHeaderLogo from './components/ReHeaderLogo/ReHeaderLogo.vue';
import ReTab from './components/ReTab/ReTab.vue';
import ReToaster from './components/ReToaster/ReToaster.vue';

// Export components
export {
    ReAppBreadcrumb,
    ReAppFooter,
    ReAppHeader,
    ReAppSidebar,
    ReCardHeader,
    ReHeaderLogo,
    ReTab,
    ReToaster,

    // ======== Core UI =============
    // Layout
    CContainer,
    CRow,
    CCol,

    // Components
    CAccordion,
    CAccordionItem,
    CAccordionHeader,
    CAccordionBody,
    CAlert,
    CAvatar,
    CBadge,
    CBreadcrumb,
    CBreadcrumbItem,
    CButton,
    CLoadingButton,
    CButtonGroup,
    CCallout,
    CCard,
    CCardHeader,
    CCardTitle,
    CCardSubtitle,
    CCardImage,
    CCardImageOverlay,
    CCardBody,
    CCardText,
    CCardLink,
    CCardFooter,
    CCarousel,
    CCarouselItem,
    CChart,
    CCloseButton,
    CCollapse,
    CDropdown,
    CDropdownToggle,
    CDropdownMenu,
    CDropdownItem,
    CDropdownDivider,
    CDropdownHeader,
    CFooter,
    CHeader,
    CHeaderToggler,
    CIcon,
    CImage,
    CLink,
    CListGroup,
    CListGroupItem,
    CModal,
    CModalHeader,
    CModalTitle,
    CModalBody,
    CModalFooter,
    CNav,
    CNavItem,
    CNavLink,
    CNavGroup,
    CNavTitle,
    CTabContent,
    CTabPane,
    CNavbar,
    CNavbarBrand,
    CNavbarNav,
    CNavbarText,
    CNavbarToggler,
    COffcanvas,
    COffcanvasHeader,
    COffcanvasTitle,
    COffcanvasBody,
    CPagination,
    CPaginationItem,
    CSmartPagination,
    CPlaceholder,
    CPopover,
    CProgress,
    CProgressBar,
    CSidebar,
    CSidebarBrand,
    CSidebarNav,
    CSidebarToggler,
    CSidebarHeader,
    CSidebarFooter,
    CSmartTable,
    CSpinner,
    CTable,
    CTableCaption,
    CTableHead,
    CTableBody,
    CTableRow,
    CTableDataCell,
    CTableHeaderCell,
    CToaster,
    CToast,
    CToastHeader,
    CToastBody,
    CTooltip,
    CWidgetStatsA,
    CWidgetStatsB,
    CWidgetStatsC,
    CWidgetStatsD,
    CWidgetStatsE,
    CWidgetStatsF,

    // Forms
    CForm,
    CFormCheck,
    CDatePicker,
    CDateRangePicker,
    CFormFloating,
    CFormInput,
    CInputGroup,
    CInputGroupText,
    CMultiSelect,
    CFormLabel,
    CFormPlugin,
    CFormText,
    CFormFeedback,
    CFormRange,
    CFormSelect,
    CFormSwitch,
    CFormTextarea,
    CTimePicker
};
